CAKOI-main/Admin/Controllers/AdminDanhMucSPController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SellFishLuxury.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SellFishLuxury.Areas.Admin.Controllers
{   [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class AdminDanhMucSPController : Controller
    {
        private WebBanHangDBContext db;
        public AdminDanhMucSPController(WebBanHangDBContext _db)
        {
            db = _db;
        }
        public IActionResult Index()
        {
            //b1. Lấy tất cả danh mục Category từ CSDL
            List<DanhMucSP> dsdanhmucSP = db.DanhMucSPs.ToList();
            // b2.truyền qua view
            return View(dsdanhmucSP);
        }
        public IActionResult Create()
        {
            return View();
        }
        //action tiếp nhận xử lý yêu cầu thêm mới danh muc sp
        [HttpPost]
        public IActionResult Create(DanhMucSP objCategory)
        {
            if (ModelState.IsValid) //kiem tra hop le du lieu
            {
                //them vao Danh muc vao CSDL
                db.DanhMucSPs.Add(objCategory);
                db.SaveChanges();
                TempData["success"] = "Category inserted success";
                //chuyen huong den action Index
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult Edit(string id)
        {
            //truy van the loai theo id
            var objCategory = db.DanhMucSPs.Find(id);
            if (objCategory == null)
            {
                return NotFound();
            }
            //tra ve view edit
            return View(objCategory);
        }
        [HttpPost]
        public IActionResult Edit(DanhMucSP objCategory)
        {
            if (ModelState.IsValid) //kiem tra hop le du lieu
            {
                //cập nhật vao category vao CSDL
                db.DanhMucSPs.Update(objCategory);
                //hoặc lệnh db.Entry<Category>(objCategory).State = EntityState.Modified;
                db.SaveChanges();
                //chuyen huong den action Index
                return RedirectToAction("Index");
            }
            return View();

        }
        public IActionResult Delete(string id)
        {
            //truy van the loai theo id
            var objCategory = db.DanhMucSPs.Find(id);
            if (objCategory == null)
            {
                return NotFound();
            }
            //tra ve view edit
            return View(objCategory);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(string id)
        {
            // truy van the loai theo id
            var objCategory = db.DanhMucSPs.Find(id);
            if (objCategory == null)
            {
                return NotFound();
            }
            //xoá
            db.DanhMucSPs.Remove(objCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

CAKOI-main/Admin/Controllers/AdminLoaiSPController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SellFishLuxury.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SellFishLuxury.Areas.Admin.Controllers
{       [Area("Admin")]
        [Authorize(Roles = SD.Role_Admin)]
    public class AdminLoaiSPController : Controller
    {
        private WebBanHangDBContext db;
        public AdminLoaiSPController(WebBanHangDBContext _db)
        {
            db = _db;
        }
        public IActionResult Index(int? page)
        {
            int pageSize = 7;
            int pageIndex;

            pageIndex = page == null ? 1 : (int)page;
            var dsloaiSP = db.LoaiSPs.Include(x => x.DanhMucSP).ToList();
            // var pageCount = Math.Ceiling((double)lstProduct.Count / pageSize);
            var pageCount = dsloaiSP.Count / pageSize + (dsloaiSP.Count % pageSize > 0 ? 1 : 0);
            //gửi qua View
            ViewBag.PageSum = pageCount;
            ViewBag.PageIndex = pageIndex;
            return View(dsloaiSP.Skip((pageIndex - 1) * pageSize).Take(pageSize).ToList());
        }
        [HttpPost]

        public IActionResult Index(string id)
        {
            var obj = db.LoaiSPs.Find(id);
            var lispr = db.LoaiSPs.Where(w => w.IdDanhMucSP == obj.IdDanhMucSP).Take(6);
            ViewBag.listPR = lispr;
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }
        public IActionResult Create()
        {
            //truyen danh sach the loai cho view de sinh ra dieu kien drowdown
            ViewBag.xListDanhMucSP = db.DanhMucSPs.Select(x => new SelectListItem { Value = x.IdDanhMucSP.ToString(), Text = x.TenDanhMucSP });
            return View();
        }

        //action tiếp nhận xử lý yêu cầu thêm mới loaisp
        [HttpPost]

        public IActionResult Create(LoaiSP objloaiSP)
        {
            if (ModelState.IsValid) //kiem tra hop le du lieu
            {
                //them vao Danh muc vao CSDL
                db.LoaiSPs.Add(objloaiSP);
                db.SaveChanges();
                TempData["success"] = "lsp inserted success";
                //chuyen huong den action Index
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Edit(string id)
        {
            //truy van the loai theo id
            var objLoaiSP = db.LoaiSPs.Find(id);
            if (objLoaiSP == null)
            
                return NotFound();
            ViewBag.xListDanhMucSP = db.DanhMucSPs.Select(x => new SelectListItem { Value = x.IdDanhMucSP.ToString(), Text = x.TenDanhMucSP });
            //tra ve view edit
            return View(objLoaiSP);
        }
        [HttpPost]
        public IActionResult Edit(LoaiSP objLoaiSP)
        {
            if (ModelState.IsValid) //kiem tra hop le du lieu
            {
                //cập nhật vao category vao CSDL
                db.LoaiSPs.Update(objLoaiSP);
                //hoặc lệnh db.Entry<Category>(objCategory).State = EntityState.Modified;
                db.SaveChanges();
                //chuyen huong den action Index
                return RedirectToAction("Index");
            }
            return View();

        }
        

        public IActionResult Delete(string id)
        {
            //truy van the loai theo id
            var objLoaiSP = db.LoaiSPs.Find(id);
            if (objLoaiSP == null)
            {
                return NotFound();
            }
            ViewBag.xListDanhMucSP = db.DanhMucSPs.Select(x => new SelectListItem { Value = x.IdDanhMucSP.ToString(), Text = x.TenDanhMucSP });
            //tra ve view edit
            return View(objLoaiSP);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(string id)
        {
            // truy van the loai theo id
            var objLoaiSP = db.LoaiSPs.Find(id);
            if (objLoaiSP == null)
            {
                return NotFound();
            }
            //xoá
            db.LoaiSPs.Remove(objLoaiSP);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

CAKOI-main/Admin/Controllers/AdminSanPhamController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SellFishLuxury.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace SellFishLuxury.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class AdminSanPhamController : Controller
    {

        private WebBanHangDBContext db;
        private IHostingEnvironment host;
        public AdminSanPhamController(WebBanHangDBContext _db, IHostingEnvironment _host)
        {
            db = _db;
            host = _host;
        }
        public IActionResult Index(string iddm ,string id,string Search, int? page )
        {

            String Loai = id;
            String pSearch = Search;
            ViewBag.xListLoaiSP = db.LoaiSPs.Where(w => w.IdDanhMucSP == iddm).ToList();
            ViewBag.xListDanhMucSP = db.DanhMucSPs.OrderBy(w => w.TenDanhMucSP).Select(d => d);
            ViewBag.listsptl = db.SanPhams.Where(s => s.IdLoaicSP == id).ToList();
            ViewBag.Loai = Loai;
            ViewBag.pSearch = pSearch;
            db.SanPhams.Include(x => x.LoaiSP).ToList();
            db.SanPhams.Include(x => x.MauSac).ToList();
            db.SanPhams.Include(x => x.TonKho).ToList();
            int pagesize = 6;
            int pageindext = 1;
            if (page == null)
            {

                pageindext = 1;
            }
            else
            {

                pageindext = (int)page;
            }
            if (id != null || Search != null)
            {
                var dsProduct = db.SanPhams.Where(w => w.IdLoaicSP == id || w.TenSanPham.ToLower().Contains(Search)).ToList();
                var Pagesum = dsProduct.Count / pagesize + (dsProduct.Count % pagesize > 0 ? 1 : 0);
           
            ViewBag.Pagesum = Pagesum;
            ViewBag.pageindext = pageindext;
            return View(dsProduct.Skip((pageindext - 1) * pagesize).Take(pagesize).ToList());
            }
            else { 
               var dsProduct = db.SanPhams.ToList();
                var Pagesum = dsProduct.Count / pagesize + (dsProduct.Count % pagesize > 0 ? 1 : 0);

                ViewBag.Pagesum = Pagesum;
                ViewBag.pageindext = pageindext;
                return View(dsProduct.Skip((pageindext - 1) * pagesize).Take(pagesize).ToList());
            }
         
           
            
           
            //String Loai = id;
            //ViewBag.xListLoaiSP = db.LoaiSPs.Where(w => w.IdDanhMucSP == iddm).ToList();
            //ViewBag.xListDanhMucSP = db.DanhMucSPs.OrderBy(w => w.TenDanhMucSP).ToList();
            //ViewBag.listsptl = db.SanPhams.Where(s => s.IdLoaicSP == id).ToList();
            //ViewBag.Loai = Loai;
            //db.SanPhams.Include(x => x.LoaiSP).ToList();
            //db.SanPhams.Include(x => x.MauSac).ToList();
            //db.SanPhams.Include(x => x.TonKho).ToList();
            //int pagesize = 6;
            //int pageindext = 1;

            //if (iddm==null & id == null & page == null)
            //{
            //    iddm = "CS";
            //    id = "PS";
            //    pageindext = 1;
            //}
            //else
            //{
            //    id = id;
            //}
            //if (page == null)
            //{

            //    pageindext = 1;
            //}
            //else
            //{

            //    pageindext = (int)page;
            //}

            ////truy van du lieu co phan trang theo pageindex va pagesize
            //var dsProduct = db.SanPhams.Where(w => w.IdLoaicSP == id).ToList();
            ////thong ke tong trang co the co 
            //var Pagesum = dsProduct.Count / pagesize + (dsProduct.Count % pagesize > 0 ? 1 : 0);
            ////var dsProduct = db.Products.Include(x=> x.Category).Skip((pageindext-1)*pagesize).Take(pagesize).ToList();
            ////truyen pagesum qua view
            //ViewBag.Pagesum = Pagesum;
            //ViewBag.pageindext = pageindext;
            //return View(dsProduct.Skip((pageindext - 1) * pagesize).Take(pagesize).ToList());

            //int pageSize = 5;
            //int pageIndex;

            //pageIndex = page == null ? 1 : (int)page;
            //var lsSanPham = db.SanPhams.Include(x => x.LoaiSP).ToList();
            //var lstMauSac = db.SanPhams.Include(x => x.MauSac).ToList();
            //var lstTonKho = db.SanPhams.Include(x => x.TonKho).ToList();
            //// var pageCount = Math.Ceiling((double)lstProduct.Count / pageSize);
            //var pageCount = lsSanPham.Count / pageSize + (lsSanPham.Count % pageSize > 0 ? 1 : 0);
            ////gửi qua View
            //ViewBag.PageSum = pageCount;
            //ViewBag.PageIndex = pageIndex;
            //return View(lsSanPham.Skip((pageIndex - 1) * pageSize).Take(pageSize).ToList());
        }

        public IActionResult Create()
        {
            //truyen danh sach the loai cho view de sinh ra dieu kien drowdown
            ViewBag.xListLoaiSP = db.LoaiSPs.Select(x => new SelectListItem { Value = x.IdLoaiSP.ToString(), Text = x.TenLoaiSP });
            ViewBag.xListMauSac = db.MauSacs.Select(x => new SelectListItem { Value = x.IdMauSac.ToString(), Text = x.TenMau });
            ViewBag.xListTonKho = db.TonKhos.Select(x => new SelectListItem { Value = x.IdSPTonKho.ToString(), Text = x.SoLuong.ToString() });
            return View();
        }
        //[HttpPost, ActionName("Create")]
        [HttpPost]
        public IActionResult Create(SanPham obj, IFormFile file)
        {
            //kiem tra hop le du lieu nhap vao 
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    //xu ly upload
                    // lay ten file(su dung gui thi ten file duoc tao tra la duy nhat)
                    string filename = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    //lay duong dan 
                    //string path = hostingEnviroment.WebRootPath + "/uploads/";
                    string path = Path.Combine(host.WebRootPath, @"AdminAssets/assets/img");
                    //sao chep len sever
                    using (var filestream = new FileStream(Path.Combine(path, filename), FileMode.Create))
                    {
                        file.CopyTo(filestream);
                    }
                    obj.Anh = @"AdminAssets/assets/img/" + filename;
                }
                //them obj vao table Products 
                db.SanPhams.Add(obj);
                db.SaveChanges();
                TempData["success"] = "Product inserted success";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Edit(int id)
        {

            //truy van Products theo id
            var obj = db.SanPhams.Find(id);
            if (obj == null)
                return NotFound();
            ViewBag.ListLoai = db.LoaiSPs.Select(x => new SelectListItem { Value = x.IdLoaiSP.ToString(), Text = x.TenLoaiSP });
            ViewBag.ListMau = db.MauSacs.Select(x => new SelectListItem { Value = x.IdMauSac.ToString(), Text = x.TenMau });
            ViewBag.ListTon = db.TonKhos.Select(x => new SelectListItem { Value = x.IdSPTonKho.ToString(), Text = x.SoLuong.ToString() });
            var lstTonKho = db.SanPhams.Include(x => x.TonKho).ToList();
            return View(obj);
        }
        [HttpPost]

        public IActionResult Edit(SanPham obj, IFormFile file)
        {
            //kiem tra hop le du lieu nhap vao 
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    //xu ly upload
                    // lay ten file(su dung gui thi ten file duoc tao tra la duy nhat)
                    string filename = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    //lay duong dan
                    string path = Path.Combine(host.WebRootPath, @"AdminAssets/assets/img");
                    using (var filestream = new FileStream(Path.Combine(path, filename), FileMode.Create))
                    {
                        file.CopyTo(filestream);
                    }
                    //sao chep len server

                    //xoa img cu cua san pham

                    if (!String.IsNullOrEmpty(obj.Anh))
                    {
                        var oldfile = Path.Combine(host.WebRootPath, obj.Anh);
                        if (System.IO.File.Exists(oldfile))
                        {
                            System.IO.File.Delete(oldfile);
                        }
                    }

                    obj.Anh = @"AdminAssets/assets/img/" + filename;
                }

                //them obj vao table Products 
                db.Update<SanPham>(obj);
                db.SaveChanges();
                TempData["success"] = "Product updated success";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Delete(int id)
        {
            //truy van san pham theo id
            var obj = db.SanPhams.Find(id);
            if (obj == null)
                return NotFound();
                ViewBag.ListLoai = db.LoaiSPs.Select(x => new SelectListItem { Value = x.IdLoaiSP.ToString(), Text = x.TenLoaiSP });
                ViewBag.ListMau = db.MauSacs.Select(x => new SelectListItem { Value = x.IdMauSac.ToString(), Text = x.TenMau });
                ViewBag.ListTon = db.TonKhos.Select(x => new SelectListItem { Value = x.IdSPTonKho.ToString(), Text = x.SoLuong.ToString() });
                var lstTonKho = db.SanPhams.Include(x => x.TonKho).ToList();
            return View(obj);

CAKOI-main/Admin/Views/Shared/_LayoutAdmin.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>quan li ban ca</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/AdminAssets/assets/img/favicon.png" rel="icon">
    <link href="~/AdminAssets/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/AdminAssets/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/AdminAssets/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/AdminAssets/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/AdminAssets/assets/vendor/quill/quill.snow.css" rel="stylesheet">
    <link href="~/AdminAssets/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
    <link href="~/AdminAssets/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/AdminAssets/assets/vendor/simple-datatables/style.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/AdminAssets/assets/css/style.css" rel="stylesheet" />
    <!-- =======================================================
    * Template Name: NiceAdmin
    * Updated: Aug 30 2023 with Bootstrap v5.3.1
    * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">

        <div class="d-flex align-items-center justify-content-between">
                   </div><!-- End Logo -->



        @using (Html.BeginForm("Index", "", FormMethod.Get))
        {
            <div class="btn-group search-bar" role="group" aria-label="Basic example">
                @Html.TextBox("Search", null, new { placeholder = "Nhập để tìm kiếm ", @class = "form-control" })
                <button type="submit" class="btn btn-primary"><i class="bi bi-search"></i>  </button>
            </div>


        }


        <!-- End Search Bar -->

        <nav class="header-nav ms-auto">
            <ul class="d-flex align-items-center">

                <li class="nav-item d-block d-lg-none">
                    <a class="nav-link nav-icon search-bar-toggle " href="#">
                    </a>
                </li><!-- End Search Icon-->

                <li class="nav-item dropdown">

                    <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
                        <i class="bi bi-bell"></i>
                        <span class="badge bg-primary badge-number">4</span>
                    </a><!-- End Notification Icon -->

                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">
                        <li class="dropdown-header">
                            You have 4 new notifications
                            <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li class="notification-item">
                            <i class="bi bi-exclamation-circle text-warning"></i>
                            <div>
                                <h4>Lorem Ipsum</h4>
                                <p>Quae dolorem earum veritatis oditseno</p>
                                <p>30 min. ago</p>
                            </div>
                        </li>

                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li class="notification-item">
                            <i class="bi bi-x-circle text-danger"></i>
                            <div>
                                <h4>Atque rerum nesciunt</h4>
                                <p>Quae dolorem earum veritatis oditseno</p>
                                <p>1 hr. ago</p>
                            </div>
                        </li>

                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li class="notification-item">
                            <i class="bi bi-check-circle text-success"></i>
                            <div>
                                <h4>Sit rerum fuga</h4>
                                <p>Quae dolorem earum veritatis oditseno</p>
                                <p>2 hrs. ago</p>
                            </div>
                        </li>

                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li class="notification-item">
                            <i class="bi bi-info-circle text-primary"></i>
                            <div>
                                <h4>Dicta reprehenderit</h4>
                                <p>Quae dolorem earum veritatis oditseno</p>
                                <p>4 hrs. ago</p>
                            </div>
                        </li>

                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li class="dropdown-footer">
                            <a href="#">Show all notifications</a>
                        </li>

                    </ul><!-- End Notification Dropdown Items -->

                </li><!-- End Notification Nav -->

                <li class="nav-item dropdown">

                    <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
                        <i class="bi bi-chat-left-text"></i>
                        <span class="badge bg-success badge-number">3</span>
                    </a><!-- End Messages Icon -->

                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow messages">
                        <li class="dropdown-header">
                            You have 3 new messages
                            <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li class="message-item">
                            <a href="#">
                                <img src="assets/img/messages-1.jpg" alt="" class="rounded-circle">
                                <div>
                                    <h4>Maria Hudson</h4>
                                    <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                                    <p>4 hrs. ago</p>
                                </div>
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li class="message-item">
                            <a href="#">
                                <img src="assets/img/messages-2.jpg" alt="" class="rounded-circle">
                                <div>
                                    <h4>Anna Nelson</h4>
                                    <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                                    <p>6 hrs. ago</p>
                                </div>
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li class="message-item">
                            <a href="#">
                                <img src="assets/img/messages-3.jpg" alt="" class="rounded-circle">
                                <div>
                                    <h4>David Muldon</h4>
                                    <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                                    <p>8 hrs. ago</p>
                                </div>
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li class="dropdown-footer">
                            <a href="#">Show all messages</a>
                        </li>

                    </ul><!-- End Messages Dropdown Items -->

                </li><!-- End Messages Nav -->

                <li class="nav-item dropdown pe-3">

                    <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                        <img src="assets/img/profile-img.jpg" alt="" class="rounded-circle">
                        <span class="d-none d-md-block dropdown-toggle ps-2">@UserManager.GetUserName(User)!</span>
                    </a><!-- End Profile Iamge Icon -->

                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                        <li class="dropdown-header">
                            <h6<partial name="_LoginPartial" /></h6>
                        </li>


                    </ul><!-- End Profile Dropdown Items -->
                </li><!-- End Profile Nav -->

            </ul>
        </nav><!-- End Icons Navigation -->

    </header><!-- End Header -->
    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">

        <ul class="sidebar-nav" id="sidebar-nav">
            @* ---------------------------------Menu---------------------------------------------- *@

            <li class="nav-item">
                <a class="nav-link collapsed" asp-area="Admin" asp-controller="AdminDanhMucSP" asp-action="Index">
                    <i class="bi bi-menu-button-wide"></i>
                    <span>Quản lí danh mục sản phẩm</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" asp-area="Admin" asp-controller="AdminLoaiSP" asp-action="Index">
                    <i class="bi bi-menu-button-wide"></i>
                    <span> Quản lí loại sản phẩm</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" asp-area="Admin" asp-controller="AdminSanPham" asp-action="Index">
                    <i class="bi bi-menu-button-wide"></i>
                    <span> Quản lí loại sản phẩm</span>
                </a>
            </li>


            <li class="nav-item">
                <a class="nav-link collapsed" asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="bi bi-box-arrow-in-right"></i>
                    <span>Quay về User</span>
                </a>
            </li>
        </ul>
    </aside>
    @RenderBody()


    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
    <!-- Vendor JS Files -->
    <script src="~/AdminAssets/assets/vendor/apexcharts/apexcharts.min.js"></script>
    <script src="~/AdminAssets/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/AdminAssets/assets/vendor/chart.js/chart.umd.js"></script>
    <script src="~/AdminAssets/assets/vendor/echarts/echarts.min.js"></script>
    <script src="~/AdminAssets/assets/vendor/quill/quill.min.js"></script>
    <script src="~/AdminAssets/assets/vendor/simple-datatables/simple-datatables.js"></script>
    <script src="~/AdminAssets/assets/vendor/tinymce/tinymce.min.js"></script>
    <script src="~/AdminAssets/assets/vendor/php-email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="~/AdminAssets/assets/js/main.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>x
    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>

CAKOI-main/Admin/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script>
toastr.success('@TempData["success"]')
    </script>
} @if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script>
toastr.error('@TempData["error"]')
    </script>
}